# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arda/CLionProjects/aytdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arda/CLionProjects/aytdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arda/CLionProjects/aytdb/CMakeFiles /Users/arda/CLionProjects/aytdb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arda/CLionProjects/aytdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aytdb

# Build rule for target.
aytdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aytdb
.PHONY : aytdb

# fast build rule for target.
aytdb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/build
.PHONY : aytdb/fast

#=============================================================================
# Target rules for targets named aytdb_server

# Build rule for target.
aytdb_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aytdb_server
.PHONY : aytdb_server

# fast build rule for target.
aytdb_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/build
.PHONY : aytdb_server/fast

#=============================================================================
# Target rules for targets named aytdb_test

# Build rule for target.
aytdb_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aytdb_test
.PHONY : aytdb_test

# fast build rule for target.
aytdb_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/build
.PHONY : aytdb_test/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named run_server

# Build rule for target.
run_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_server
.PHONY : run_server

# fast build rule for target.
run_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_server.dir/build.make CMakeFiles/run_server.dir/build
.PHONY : run_server/fast

hash_util.o: hash_util.c.o
.PHONY : hash_util.o

# target to build an object file
hash_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/hash_util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/hash_util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/hash_util.c.o
.PHONY : hash_util.c.o

hash_util.i: hash_util.c.i
.PHONY : hash_util.i

# target to preprocess a source file
hash_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/hash_util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/hash_util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/hash_util.c.i
.PHONY : hash_util.c.i

hash_util.s: hash_util.c.s
.PHONY : hash_util.s

# target to generate assembly for a file
hash_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/hash_util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/hash_util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/hash_util.c.s
.PHONY : hash_util.c.s

kv_store.o: kv_store.c.o
.PHONY : kv_store.o

# target to build an object file
kv_store.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/kv_store.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/kv_store.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/kv_store.c.o
.PHONY : kv_store.c.o

kv_store.i: kv_store.c.i
.PHONY : kv_store.i

# target to preprocess a source file
kv_store.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/kv_store.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/kv_store.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/kv_store.c.i
.PHONY : kv_store.c.i

kv_store.s: kv_store.c.s
.PHONY : kv_store.s

# target to generate assembly for a file
kv_store.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/kv_store.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/kv_store.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/kv_store.c.s
.PHONY : kv_store.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/main.c.s
.PHONY : main.c.s

server.o: server.c.o
.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/server.c.s
.PHONY : server.c.s

server_main.o: server_main.c.o
.PHONY : server_main.o

# target to build an object file
server_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/server_main.c.o
.PHONY : server_main.c.o

server_main.i: server_main.c.i
.PHONY : server_main.i

# target to preprocess a source file
server_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/server_main.c.i
.PHONY : server_main.c.i

server_main.s: server_main.c.s
.PHONY : server_main.s

# target to generate assembly for a file
server_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/server_main.c.s
.PHONY : server_main.c.s

storage.o: storage.c.o
.PHONY : storage.o

# target to build an object file
storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/storage.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/storage.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/storage.c.o
.PHONY : storage.c.o

storage.i: storage.c.i
.PHONY : storage.i

# target to preprocess a source file
storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/storage.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/storage.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/storage.c.i
.PHONY : storage.c.i

storage.s: storage.c.s
.PHONY : storage.s

# target to generate assembly for a file
storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb.dir/build.make CMakeFiles/aytdb.dir/storage.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_server.dir/build.make CMakeFiles/aytdb_server.dir/storage.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/storage.c.s
.PHONY : storage.c.s

test_runner.o: test_runner.c.o
.PHONY : test_runner.o

# target to build an object file
test_runner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/test_runner.c.o
.PHONY : test_runner.c.o

test_runner.i: test_runner.c.i
.PHONY : test_runner.i

# target to preprocess a source file
test_runner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/test_runner.c.i
.PHONY : test_runner.c.i

test_runner.s: test_runner.c.s
.PHONY : test_runner.s

# target to generate assembly for a file
test_runner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/test_runner.c.s
.PHONY : test_runner.c.s

test_storage.o: test_storage.c.o
.PHONY : test_storage.o

# target to build an object file
test_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/test_storage.c.o
.PHONY : test_storage.c.o

test_storage.i: test_storage.c.i
.PHONY : test_storage.i

# target to preprocess a source file
test_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/test_storage.c.i
.PHONY : test_storage.c.i

test_storage.s: test_storage.c.s
.PHONY : test_storage.s

# target to generate assembly for a file
test_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aytdb_test.dir/build.make CMakeFiles/aytdb_test.dir/test_storage.c.s
.PHONY : test_storage.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run_server"
	@echo "... run_tests"
	@echo "... aytdb"
	@echo "... aytdb_server"
	@echo "... aytdb_test"
	@echo "... hash_util.o"
	@echo "... hash_util.i"
	@echo "... hash_util.s"
	@echo "... kv_store.o"
	@echo "... kv_store.i"
	@echo "... kv_store.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... server_main.o"
	@echo "... server_main.i"
	@echo "... server_main.s"
	@echo "... storage.o"
	@echo "... storage.i"
	@echo "... storage.s"
	@echo "... test_runner.o"
	@echo "... test_runner.i"
	@echo "... test_runner.s"
	@echo "... test_storage.o"
	@echo "... test_storage.i"
	@echo "... test_storage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

